enabled: false
# type: mysql # Currently only MySQL/MariaDB supported via JDBC URL
host: localhost
port: 3306
database: devreview
username: root
password: ""
table-prefix: "devreview_"
# pool-size: 10 # Not currently implemented
